### PR TITLE
Fix for Discord sweeping classes/elements changes

### PR DESCRIPTION
**Pull request by Aluerie**
Fix for #100. 

Looks like updating classes/elements to newest values does the trick. 

Hopefully I didn't miss anything.

### CODE REVIEW

**Comment by ColonelGerdauf** [comment]
I wonder if it is worthwhile to move the named classes to a dedicated variables section, or even a separate data file that can be updated.

**Comment by OnyxL** [comment]
But now the memberlist isn't collapsing again.
image

**Comment by programmer2514** [comment]
@ColonelGerdauf It already is consolidated within its own method, and putting it in its own file would be a lot more complicated because of how BetterDiscord handles updating plugins

@OnyxL I can't seem to reproduce this behavior on Stable; I won't be able to fix it until I can

@Aluerie Looks good to me, thank you for the contribution! And apologies for not getting around to this sooner, I've been feeling under the weather for a while so I really appreciate the help :)

**Comment by OnyxL** [comment]
@programmer2514 I fixed it by enabling UI Transitions then disables it again works fine.

**Pull request merged**
